version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80"
    depends_on:
      - postgres

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_mvc
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - postgres
